name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: algebraPolinom
      run: cmake .
    - name: make
      run: make
    - name: TestStart
      run: ./AlgebraPolinom/build/bin/test_Polynom
